// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0CEEBHuCYzbpjV5hSRQue5xdtaW-bsDM',
    appId: '1:602029980742:web:afecaffe07512409821e47',
    messagingSenderId: '602029980742',
    projectId: 'coffe-system',
    authDomain: 'coffe-system.firebaseapp.com',
    storageBucket: 'coffe-system.firebasestorage.app',
    measurementId: 'G-S7FQQDM0QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7fBJek2vrG99_-2IjmT0_9SbBUnnihPU',
    appId: '1:602029980742:android:baf1da9bb1a43cb3821e47',
    messagingSenderId: '602029980742',
    projectId: 'coffe-system',
    storageBucket: 'coffe-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz8LUgZXP3msSmHJnuGEuSmmRyC2268cU',
    appId: '1:602029980742:ios:ce865ad3d78d4f88821e47',
    messagingSenderId: '602029980742',
    projectId: 'coffe-system',
    storageBucket: 'coffe-system.firebasestorage.app',
    iosBundleId: 'com.example.coffeSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz8LUgZXP3msSmHJnuGEuSmmRyC2268cU',
    appId: '1:602029980742:ios:ce865ad3d78d4f88821e47',
    messagingSenderId: '602029980742',
    projectId: 'coffe-system',
    storageBucket: 'coffe-system.firebasestorage.app',
    iosBundleId: 'com.example.coffeSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0CEEBHuCYzbpjV5hSRQue5xdtaW-bsDM',
    appId: '1:602029980742:web:0ddce06d35fec4ea821e47',
    messagingSenderId: '602029980742',
    projectId: 'coffe-system',
    authDomain: 'coffe-system.firebaseapp.com',
    storageBucket: 'coffe-system.firebasestorage.app',
    measurementId: 'G-D87S4NJZEB',
  );
}
